spring.application.name=cozyhavenstay

# --- MySQL Database Configuration ---
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/cozy_haven_stay_app?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA/Hibernate Configuration ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# --- JWT Configuration (initial placeholders - will be detailed later) ---
jwt.secret=gUk1tRPm2It6qVBhwSwh72eapXLzyK2NIhKwGp7uUNA=
jwt.expiration=86400000

# ----------Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sudharsanainbakumar2003@gmail.com
spring.mail.password=rxkm flnx nswx tnuh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.test-connection=false


# Frontend URL for Password Reset (IMPORTANT!)
frontend.reset.password.url=http://localhost:4200/reset-password


server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# --- Logging Configuration (Crucial for debugging transactions) ---
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.com.hexa.cozyhavenstay=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.transaction=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE



razorpay.key.id=rzp_test_P0tjvNu4sqkt2G
razorpay.key.secret=OcSrEdWCjU9SPDZmh7aNzoip


logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.type.descriptor.sql=TRACE